---

- name: download bind exporter binary
  get_url:
    url: "{{ url }}"
    dest: "{{ prometheus_exporters_common_dist_dir }}/{{ bind_exporter_release_name }}.tar.gz"

- name: unarchive binary tarball
  unarchive:
    copy: no
    src: "{{ prometheus_exporters_common_dist_dir }}/{{ bind_exporter_release_name }}.tar.gz"
    dest: "{{ prometheus_exporters_common_dist_dir }}"
    creates: "{{ prometheus_exporters_common_dist_dir }}/{{ bind_exporter_release_name }}/bind_exporter"
  register: bind_exporter_updated
  notify:
    - restart bind exporter

- name: update group and owner for files
  file:
    path: "{{ bind_exporter_release_name }}"
    state: directory
    recurse: yes
    owner: "{{ prometheus_exporters_common_user }}"
    group: "{{ prometheus_exporters_common_group }}"
  when: bind_exporter_updated is changed

- name: create symlink to the current release
  file:
    src: "{{ prometheus_exporters_common_dist_dir }}/{{ bind_exporter_release_name }}"
    path: "{{ prometheus_exporters_common_root_dir }}/bind_exporter_current"
    state: link

- name: create systemd service unit
  template:
    src: etc/systemd/system/bind_exporter.service.j2
    dest: /etc/systemd/system/bind_exporter.service
    owner: root
    group: root
    mode: 0644
  when: service_mgr | default(ansible_service_mgr) == 'systemd'
  notify:
    - reenable bind exporter service
    - restart bind exporter

- name: Looking which version of upstart is install
  command: initctl version
  when: service_mgr | default(ansible_service_mgr) == 'upstart'
  register: upstart_version
  changed_when: false

- name: create init service unit
  template:
    src: etc/init/bind_exporter.conf.j2
    dest: /etc/init/bind_exporter.conf
    owner: root
    group: root
    mode: 0644
  when: service_mgr | default(ansible_service_mgr) == 'upstart'
  notify:
    - reinit bind exporter
    - restart bind exporter

- name: create sysvinit service unit
  template:
    src: etc/init.d/bind_exporter.j2
    dest: /etc/init.d/bind_exporter
    owner: root
    group: root
    mode: 0755
  when: service_mgr | default(ansible_service_mgr) in [ 'sysvinit', 'service' ]
  notify:
    - restart bind exporter

- meta: flush_handlers

- name: ensure bind exporter service is enabled and started
  service:
    name: bind_exporter
    state: started
    enabled: yes
