---

- name: reenable bind exporter service
  service:
    name: bind_exporter.service
    state: enabled

- name: reinit bind exporter
  command: initctl reload-configuration

- name: restart bind exporter
  service:
    name: bind_exporter
    state: restarted
