---

- name: reenable bind exporter service
  systemd:
    name: bind_exporter.service
    state: enabled
  when: ansible_distribution_version >= '7'

- name: reinit bind exporter
  command: initctl reload-configuration

- name: restart bind exporter
  service:
    name: bind_exporter
    state: restarted
